# Generated by Django 2.2 on 2019-04-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_search', '0001_squashed_0003_auto_20190422_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_search.Employees'),
        ),
        migrations.DeleteModel(
            name='Dept_Manager',
        ),
    ]
