# Generated by Django 2.2 on 2019-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
