# Generated by Django 2.2 on 2019-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_search', '0002_auto_20190422_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Salaries',
        ),
    ]
